/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  NiftyUploader,
} from 'nifty-uploader';


export namespace Components {

  interface NiftyAddButton {
    /**
    * The uploader
    */
    'uploader': NiftyUploader;
  }
  interface NiftyAddButtonAttributes extends StencilHTMLAttributes {
    /**
    * The uploader
    */
    'uploader'?: NiftyUploader;
  }

  interface NuUploader {
    'uploader': NiftyUploader;
  }
  interface NuUploaderAttributes extends StencilHTMLAttributes {
    'uploader'?: NiftyUploader;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NiftyAddButton': Components.NiftyAddButton;
    'NuUploader': Components.NuUploader;
  }

  interface StencilIntrinsicElements {
    'nifty-add-button': Components.NiftyAddButtonAttributes;
    'nu-uploader': Components.NuUploaderAttributes;
  }


  interface HTMLNiftyAddButtonElement extends Components.NiftyAddButton, HTMLStencilElement {}
  var HTMLNiftyAddButtonElement: {
    prototype: HTMLNiftyAddButtonElement;
    new (): HTMLNiftyAddButtonElement;
  };

  interface HTMLNuUploaderElement extends Components.NuUploader, HTMLStencilElement {}
  var HTMLNuUploaderElement: {
    prototype: HTMLNuUploaderElement;
    new (): HTMLNuUploaderElement;
  };

  interface HTMLElementTagNameMap {
    'nifty-add-button': HTMLNiftyAddButtonElement
    'nu-uploader': HTMLNuUploaderElement
  }

  interface ElementTagNameMap {
    'nifty-add-button': HTMLNiftyAddButtonElement;
    'nu-uploader': HTMLNuUploaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
